import { SVGProps } from "react";

import { IBlogCardProps } from "./type/card";

export interface SocialMediaProps {
  id: string;
  url: string;
  icon: (props: SVGProps<SVGSVGElement>) => JSX.Element;
}

export interface RoutingProps {
  url: string;
  content: string;
}

export const NAV_BTN_INFO_LIST: RoutingProps[] = [
  {
    url: "/about",
    content: "About",
  },
  {
    url: "/blogs",
    content: "Blogs",
  },
  {
    url: "/projects",
    content: "Projects",
  },
  {
    url: "/contact",
    content: "Contact",
  },
];

export const BLOG_INFO_DICT: { [id: string]: IBlogCardProps } = {
  great_ytb_channels_1: {
    content_section: "Blogs",
    id: "great_ytb_channels_1",
    title: "Great Youtube Channels (Part 1)",
    brief_description: `I watch youtube a lot, and I make a list of youtube channels \
I have watched that you may find interesting. Here is part 1 of my list...`,
    url: "/great_ytb_channels_1",
    file: "great_ytb_channels_1.md",
    tags: ["casual"],
    date: new Date("Apr 26 2023 22:35:23 GMT+0800"),
  },
  great_ytb_channels_2: {
    content_section: "Blogs",
    id: "great_ytb_channels_2",
    title: "Great Youtube Channels (Part 2)",
    brief_description: `I watch youtube a lot, and I make a list of youtube channels \
I have watched that you may find interesting. Here is part 2 of my list...`,
    url: "/great_ytb_channels_2",
    file: "great_ytb_channels_2.md",
    date: new Date("Apr 27 2023 13:30:59 GMT+0800"),
    tags: ["casual"],
  },
  markdown_starter: {
    content_section: "Blogs",
    id: "markdown_starter",
    title: "Get Started with Markdown",
    brief_description: "My markdown theme which is generated by React Markdown.",
    url: "/markdown_starter",
    file: "markdown_starter.md",
    tags: ["casual"],
    date: new Date("Thu Mar 23 2023 23:10:33 GMT+0700"),
  },
  uncommon_javascript_notes: {
    content_section: "Blogs",
    id: "uncommon_javascript_notes",
    title: "Uncommon JavaScript Notes - The Language",
    brief_description: `JavaScript is super complicated, like a pain in your ass. \
Even when you are quite familiar with programming languages logics and concepts, \
you still find it difficult to cover major aspects in JS.`,
    url: "/uncommon_javascript_notes",
    file: "uncommon_javascript_notes.md",
    tags: ["javascript", "code"],
    date: new Date("Fri Jun 16 2023 23:02:26 GMT+0700"),
  },
  uncommon_javascript_notes_1: {
    content_section: "Blogs",
    id: "uncommon_javascript_notes_1",
    title: "Uncommon JavaScript Notes - Browser: Document, Events, Interfaces",
    brief_description: `One thing that make JavaScript weird to learn is \
how it interacts with the browser DOM, how to control the events, the forms, \
and how the resource is loaded.`,
    url: "/uncommon_javascript_notes_1",
    file: "uncommon_javascript_notes_1.md",
    tags: ["javascript", "code"],
    date: new Date("Sun Sep 03 2023 11:13:44 GMT+0700"),
  },
  learn_from_react_bun_boilerplate: {
    content_section: "Blogs",
    id: "learn_from_react_bun_boilerplate",
    title: "What I Learned After Re-creating a React Boilerplate",
    brief_description: `We can learn by re-creating something. This post is \
about which things I discovered just by a React boilerplate.`,
    url: "/learn_from_react_bun_boilerplate",
    file: "react_bun_boilerplate.md",
    tags: ["bun", "typescript", "code"],
    date: new Date("Sun Oct 22 2023 19:43:00 GMT+0700"),
  },
  data_adapter_template: {
    content_section: "Blogs",
    id: "data_adapter_template",
    title: "A Template for Building Your Own Data Migration Code",
    brief_description: `Imagine you are facing a complex data migration task scenario involving \
many data sources and intricate transformations. You want to build an efficient script to migrate \
the data, what is your solution?`,
    url: "/data_adapter_template",
    file: "data_adapter_template.md",
    tags: ["typescript", "oop", "code"],
    date: new Date("Fri Mar 15 2024 13:58:21 GMT+0700"),
  },
};

export const BLOG_INFO_LIST: { dictKey: string; date: string }[] = [
  { dictKey: "great_ytb_channels_1", date: "Apr 26 2023 22:35:23 GMT+0800" },
  { dictKey: "great_ytb_channels_2", date: "Apr 27 2023 13:30:59 GMT+0800" },
  { dictKey: "markdown_starter", date: "Thu Mar 23 2023 23:10:33 GMT+0700" },
  {
    dictKey: "uncommon_javascript_notes",
    date: "Fri Jun 16 2023 23:02:26 GMT+0700",
  },
  {
    dictKey: "uncommon_javascript_notes_1",
    date: "Sun Sep 03 2023 11:13:44 GMT+0700",
  },
  {
    dictKey: "learn_from_react_bun_boilerplate",
    date: "Sun Oct 22 2023 19:43:00 GMT+0700",
  },
  { dictKey: "data_adapter_template", date: "Fri Mar 15 2024 13:58:21 GMT+0700" },
];
