import type { Metadata } from "next";
import { Space_Grotesk } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/global/theme-provider";
import NavBar from "@/components/layout/navbar";
import Transition from "@/utils/transition";
import MobileNavBar from "@/components/layout/mobileNavbar";
const font = Space_Grotesk({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Thang Vu // Home",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={font.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <div className="flex justify-between w-full h-full relative">
            <div className="fixed w-[6%] h-full z-50 hidden md:block">
              <NavBar />
            </div>
            <div className="top-0 w-full block lg:hidden md:hidden items-center justify-center backdrop-blur-md absolute z-60">
              <MobileNavBar/>
            </div>
            <Transition>{children}</Transition>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
