import type { Metadata } from "next";
import { Inter, Space_Grotesk } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/global/theme-provider";
import NavBar from "@/components/layout/navbar";
import Footer from "@/components/layout/footer";

const font = Space_Grotesk({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Thang Vu // Home",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={font.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <div className="flex justify-between w-full h-full">
            <div className="fixed w-[6%] h-full z-50 lg:flex md:flex hidden">
              <NavBar />
            </div>
            <div className="flex w-full px-4 items-center justify-center">
              {children}
            </div>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
